name: Dynamic View Bot with Screenshot

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'URL Link'
        required: true
        default: 'https://bit.ly/example'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Start Automation
        env:
          TARGET_URL: ${{ github.event.inputs.site_url }}
          BOT_ENABLED: 'true'
          TAB_COUNT: '1'
        run: node bot.js

      - name: Upload Screenshot
        if: always() # Script cancel hone par bhi screenshot save hoga
        uses: actions/upload-artifact@v4
        with:
          name: site-screenshot
          path: ./*.png
